name: splace_env
channels:
  - conda-forge
  - bioconda
  - lprabelo
dependencies:
  - python=3.12
  - biopython=1.85
  - iqtree=3.0.1
  - syngenes=1.0.6
  - mafft=7.526
  - trimal=1.5.0
  - openpyxl=3.1.5